import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
	await prisma.role.createMany({
		data: [
			{
				id: "role-doctor",
				name: "Doctor",
			},
			{
				id: "role-receptionist",
				name: "Receptionist",
			},
			{
				id: "role-administrator",
				name: "Administrator",
			},
		],
	});
	await prisma.department.create({
		data: {
			id: "general-id",
			name: "General",
		},
	});
	await prisma.staff.createMany({
		data: [
			{
				id: "d1f01f67-6b20-4316-add4-81dd4415fac9",
				username: "drjohnsmith",
				password: "securepassword123",
				firstName: "John",
				middleName: "Michael",
				lastName: "Smith",
				sex: "MALE",
				birthDate: "1980-06-15T00:00:00.000Z",
				region: "Addis Ababa",
				city: "Addis Ababa",
				woreda: "04",
				kebele: "12",
				mobileNumber: "0912345678",
				email: "john.smith@example.com",
				hireDate: "2015-03-25T00:00:00.000Z",
				emergencyContact: "0911234567",
				employmentStatus: "Active",
				notes: ["Highly experienced in cardiac surgeries"],
				departmentId: "general-id",
				roleId: "role-doctor",
			},
			{
				id: "staff-002",
				username: "reception001",
				password: "securepassword456",
				firstName: "Martha",
				middleName: "Jane",
				lastName: "Doe",
				sex: "FEMALE",
				birthDate: "1992-08-20T00:00:00.000Z",
				region: "Oromia",
				city: "Adama",
				woreda: "03",
				kebele: "15",
				mobileNumber: "0912345679",
				email: "martha.doe@example.com",
				hireDate: "2018-06-01T00:00:00.000Z",
				emergencyContact: "0911234568",
				employmentStatus: "Active",
				notes: ["Excellent communication skills"],
				departmentId: "general-id",
				roleId: "role-receptionist",
			},
			{
				id: "staff-003",
				username: "admin001",
				password: "securepassword789",
				firstName: "David",
				middleName: "Andrew",
				lastName: "Johnson",
				sex: "MALE",
				birthDate: "1975-12-05T00:00:00.000Z",
				region: "Amhara",
				city: "Bahir Dar",
				woreda: "02",
				kebele: "8",
				mobileNumber: "0912345680",
				email: "david.johnson@example.com",
				hireDate: "2012-01-15T00:00:00.000Z",
				emergencyContact: "0911234569",
				employmentStatus: "Active",
				notes: ["Experienced in hospital administration"],
				departmentId: "general-id",
				roleId: "role-administrator",
			},
		],
	});
	await prisma.doctor.createMany({
		data: [
			{
				id: "84217cb9-4af4-4a92-941d-3d26fb64e2de",
				specialization: "Cardiology",
				staffId: "d1f01f67-6b20-4316-add4-81dd4415fac9",
			},
		],
	});

	await prisma.patient.createMany({
		data: [
			{
				id: "91a60e74-94ab-423f-8930-4dc130061915",
				firstName: "Thomas",
				middleName: "Shelby",
				lastName: "Limited",
				sex: "MALE",
				birthDate: "2024-02-01T10:13:14.741Z",
				region: "North-England",
				city: "Birmingham",
				woreda: "",
				kebele: null,
				mobileNumber: "111-255-2554",
				password: "",
				email: null,
				occupation: "Business Man",
				emergencyContactName: null,
				emergencyContactMobileNo: null,
			},
			{
				id: "45f62fb0-db7b-49bd-be31-db3ba3a94372",
				firstName: "John",
				middleName: "Shelby",
				lastName: "Limited",
				sex: "MALE",
				birthDate: "2024-02-01T10:14:36.728Z",
				region: "North-England",
				city: "Birmingham",
				woreda: "",
				kebele: null,
				mobileNumber: "111-155-2554",
				password: "",
				email: null,
				occupation: "Business Man",
				emergencyContactName: null,
				emergencyContactMobileNo: null,
			},
			{
				id: "6274f891-7c97-48cd-9867-31ed054144a9",
				firstName: "Arthur",
				middleName: "Shelby",
				lastName: "Limited",
				sex: "MALE",
				birthDate: "2024-02-01T10:14:52.970Z",
				region: "North-England",
				city: "Birmingham",
				woreda: "",
				kebele: null,
				mobileNumber: "111-055-2554",
				password: "",
				email: null,
				occupation: "Business Man",
				emergencyContactName: null,
				emergencyContactMobileNo: null,
			},
			{
				id: "patient-1",
				firstName: "John",
				middleName: "A.",
				lastName: "Doe",
				sex: "MALE",
				birthDate: "1990-01-01T00:00:00.000Z",
				region: "Addis Ababa",
				city: "Addis Ababa",
				woreda: "01",
				kebele: "123",
				mobileNumber: "0911000000",
				password: "hashed_password",
				email: "john.doe@example.com",
				occupation: null,
				emergencyContactName: null,
				emergencyContactMobileNo: null,
			},
			{
				id: "patient-2",
				firstName: "Jane",
				middleName: "B.",
				lastName: "Smith",
				sex: "FEMALE",
				birthDate: "1985-05-15T00:00:00.000Z",
				region: "Oromia",
				city: "Adama",
				woreda: "02",
				kebele: "456",
				mobileNumber: "0912000000",
				password: "hashed_password",
				email: "jane.smith@example.com",
				occupation: null,
				emergencyContactName: null,
				emergencyContactMobileNo: null,
			},
			{
				id: "7c3865ea-fef2-48c5-b53c-477cb61edb0a",
				firstName: "Mary",
				middleName: "Jane",
				lastName: "Parker",
				sex: "FEMALE",
				birthDate: "2003-07-10T00:00:00.000Z",
				region: "Addis Ababa",
				city: "Addis Ababa",
				woreda: "Saris Addis Sefer",
				kebele: "12",
				mobileNumber: "0985858585",
				password: "maryjane",
				email: "maryjane2003@gmail.com",
				occupation: "Student",
				emergencyContactName: "Peter Parker",
				emergencyContactMobileNo: "0909090909",
			},
			{
				id: "93d27043-d622-4784-968e-9c908d1fc409",
				firstName: "Agatha",
				middleName: "C.",
				lastName: "Wood",
				sex: "FEMALE",
				birthDate: "2000-05-04T00:00:00.000Z",
				region: "Addis Ababa",
				city: "Addis Ababa",
				woreda: "Koye",
				kebele: "1",
				mobileNumber: "0924242424",
				password: "agathawood",
				email: "agathawood@gmail.com",
				occupation: "Student",
				emergencyContactName: "Mr. Wood",
				emergencyContactMobileNo: "0932323232",
			},
			{
				id: "c59e7342-bf62-48fd-a6e5-77348e347e7d",
				firstName: "Tiffany",
				middleName: "B.",
				lastName: "Banks",
				sex: "FEMALE",
				birthDate: "1980-05-05T00:00:00.000Z",
				region: "Addis Ababa",
				city: "Addis Ababa",
				woreda: "Koye",
				kebele: "1",
				mobileNumber: "0729292929",
				password: "tiffanybanks",
				email: "tiffanybanks@gmail.com",
				occupation: "House wife",
				emergencyContactName: "George Banks",
				emergencyContactMobileNo: "0789898989",
			},
			{
				id: "9206f122-5800-4126-a557-dbbfc4b03ea0",
				firstName: "Bill",
				middleName: "A.",
				lastName: "Gatsby",
				sex: "MALE",
				birthDate: "2004-02-05T00:00:00.000Z",
				region: "Addis Ababa",
				city: "Addis Ababa",
				woreda: "Koye",
				kebele: "1",
				mobileNumber: "0940404040",
				password: "123456789",
				email: "billgatsby@gmail.com",
				occupation: "Student",
				emergencyContactName: "Andrew Gatsby",
				emergencyContactMobileNo: "0926262626",
			},
			{
				id: "47cb08d0-2042-47a2-ad7d-3ade5513947a",
				firstName: "Peter",
				middleName: "B.",
				lastName: "Parker",
				sex: "MALE",
				birthDate: "2000-10-02T00:00:00.000Z",
				region: "New York",
				city: "New York",
				woreda: "Queens",
				kebele: "",
				mobileNumber: "0909090909",
				password: "",
				email: "peterparker2000@gmail.com",
				occupation: "Superhero",
				emergencyContactName: "May Parker",
				emergencyContactMobileNo: "0910101010",
			},
		],
	});
	await prisma.diseases.createMany({
		data: [
			{ name: "Hypertension" },
			{ name: "Diabetes Mellitus" },
			{ name: "Asthma" },
			{ name: "Chronic Obstructive Pulmonary Disease (COPD)" },
			{ name: "Coronary Artery Disease" },
			{ name: "Stroke" },
			{ name: "Cancer" },
			{ name: "Alzheimer's Disease" },
			{ name: "Parkinson's Disease" },
			{ name: "Osteoporosis" },
			{ name: "Arthritis" },
			{ name: "Rheumatoid Arthritis" },
			{ name: "Osteoarthritis" },
			{ name: "Chronic Kidney Disease" },
			{ name: "Hepatitis B" },
			{ name: "Hepatitis C" },
			{ name: "HIV/AIDS" },
			{ name: "Tuberculosis" },
			{ name: "Pneumonia" },
			{ name: "Influenza" },
			{ name: "COVID-19" },
			{ name: "Migraine" },
			{ name: "Epilepsy" },
			{ name: "Multiple Sclerosis" },
			{ name: "Celiac Disease" },
			{ name: "Crohn's Disease" },
			{ name: "Ulcerative Colitis" },
			{ name: "Irritable Bowel Syndrome" },
			{ name: "Gastritis" },
			{ name: "Peptic Ulcer" },
			{ name: "Gastroesophageal Reflux Disease (GERD)" },
			{ name: "Chronic Fatigue Syndrome" },
			{ name: "Lupus" },
			{ name: "Psoriasis" },
			{ name: "Eczema" },
			{ name: "Dermatitis" },
			{ name: "Acne" },
			{ name: "Rosacea" },
			{ name: "Vitiligo" },
			{ name: "Sickle Cell Anemia" },
			{ name: "Hemophilia" },
			{ name: "Leukemia" },
			{ name: "Lymphoma" },
			{ name: "Anemia" },
			{ name: "Thalassemia" },
			{ name: "Gout" },
			{ name: "Fibromyalgia" },
			{ name: "Carpal Tunnel Syndrome" },
			{ name: "Tendonitis" },
			{ name: "Bursitis" },
			{ name: "Shingles" },
			{ name: "Chickenpox" },
			{ name: "Measles" },
			{ name: "Mumps" },
			{ name: "Rubella" },
			{ name: "Whooping Cough" },
			{ name: "Tetanus" },
			{ name: "Diphtheria" },
			{ name: "Pertussis" },
			{ name: "Polio" },
			{ name: "Malaria" },
			{ name: "Dengue" },
			{ name: "Zika Virus" },
			{ name: "Chikungunya" },
			{ name: "Yellow Fever" },
			{ name: "Rabies" },
			{ name: "Lyme Disease" },
			{ name: "Rocky Mountain Spotted Fever" },
			{ name: "Ebola" },
			{ name: "Marburg Virus" },
			{ name: "Hantavirus" },
			{ name: "Lassa Fever" },
			{ name: "Meningitis" },
			{ name: "Encephalitis" },
			{ name: "West Nile Virus" },
			{ name: "Zoster Virus" },
			{ name: "Hantavirus Pulmonary Syndrome" },
			{ name: "Middle East Respiratory Syndrome (MERS)" },
			{ name: "Severe Acute Respiratory Syndrome (SARS)" },
			{ name: "Avian Influenza" },
			{ name: "Swine Flu" },
			{ name: "Anthrax" },
			{ name: "Plague" },
			{ name: "Tularemia" },
			{ name: "Q Fever" },
			{ name: "Brucellosis" },
			{ name: "Botulism" },
			{ name: "Leptospirosis" },
			{ name: "Schistosomiasis" },
			{ name: "Trypanosomiasis" },
			{ name: "Leishmaniasis" },
			{ name: "Chagas Disease" },
			{ name: "Onchocerciasis" },
			{ name: "Filariasis" },
			{ name: "Dracunculiasis" },
			{ name: "Ascariasis" },
			{ name: "Hookworm Infection" },
			{ name: "Pinworm Infection" },
			{ name: "Toxocariasis" },
			{ name: "Strongyloidiasis" },
		],
	});

	await prisma.medication.createMany({
		data: [
			{
				id: "med-1",
				name: "Advil",
				description: "Also known as Ibuprofen",
				price: 7.99,
				available: 50,
			},
			{
				id: "med-2",
				name: "Tylenol",
				description: "Also known as Acetaminophen",
				price: 8.99,
				available: 50,
			},
			{
				name: "Aleve",
				description: "Also known as Naproxen",
				price: 9.49,
				available: 50,
			},
			{
				name: "Motrin",
				description: "Also known as Ibuprofen",
				price: 6.99,
				available: 50,
			},
			{
				name: "Aspirin",
				description: "Also known as Acetylsalicylic Acid",
				price: 4.99,
				available: 50,
			},
			{
				name: "Lisinopril",
				description: "Also known as Lisinopril",
				price: 10.0,
				available: 50,
			},
			{
				name: "Zestril",
				description: "Also known as Lisinopril",
				price: 10.0,
				available: 50,
			},
			{
				name: "Lipitor",
				description: "Also known as Atorvastatin",
				price: 13.99,
				available: 50,
			},
			{
				name: "Zocor",
				description: "Also known as Simvastatin",
				price: 12.49,
				available: 50,
			},
			{
				name: "Crestor",
				description: "Also known as Rosuvastatin",
				price: 15.0,
				available: 50,
			},
			{
				name: "Plavix",
				description: "Also known as Clopidogrel",
				price: 14.99,
				available: 50,
			},
			{
				name: "Coumadin",
				description: "Also known as Warfarin",
				price: 10.49,
				available: 50,
			},
			{
				name: "Glucophage",
				description: "Also known as Metformin",
				price: 5.0,
				available: 50,
			},
			{
				name: "Amoxil",
				description: "Also known as Amoxicillin",
				price: 8.49,
				available: 50,
			},
			{
				name: "Cipro",
				description: "Also known as Ciprofloxacin",
				price: 11.99,
				available: 50,
			},
			{
				name: "Zithromax",
				description: "Also known as Azithromycin",
				price: 12.99,
				available: 50,
			},
			{
				name: "Augmentin",
				description: "Also known as Amoxicillin/Clavulanate",
				price: 15.49,
				available: 50,
			},
			{
				name: "Lasix",
				description: "Also known as Furosemide",
				price: 4.99,
				available: 50,
			},
			{
				name: "Norvasc",
				description: "Also known as Amlodipine",
				price: 6.99,
				available: 50,
			},
			{
				name: "Prozac",
				description: "Also known as Fluoxetine",
				price: 9.99,
				available: 50,
			},
			{
				name: "Zoloft",
				description: "Also known as Sertraline",
				price: 10.99,
				available: 50,
			},
			{
				name: "Lexapro",
				description: "Also known as Escitalopram",
				price: 11.49,
				available: 50,
			},
			{
				name: "Ativan",
				description: "Also known as Lorazepam",
				price: 7.49,
				available: 50,
			},
			{
				name: "Xanax",
				description: "Also known as Alprazolam",
				price: 8.99,
				available: 50,
			},
			{
				name: "Valium",
				description: "Also known as Diazepam",
				price: 9.49,
				available: 50,
			},
			{
				name: "Ambien",
				description: "Also known as Zolpidem",
				price: 12.49,
				available: 50,
			},
			{
				name: "Lunesta",
				description: "Also known as Eszopiclone",
				price: 14.99,
				available: 50,
			},
			{
				name: "Singulair",
				description: "Also known as Montelukast",
				price: 10.99,
				available: 50,
			},
			{
				name: "Prednisone",
				description: "Also known as Prednisone",
				price: 6.49,
				available: 50,
			},
			{
				name: "Deltasone",
				description: "Also known as Prednisone",
				price: 6.49,
				available: 50,
			},
			{
				name: "Albuterol",
				description: "Also known as Albuterol",
				price: 18.99,
				available: 50,
			},
			{
				name: "ProAir",
				description: "Also known as Albuterol",
				price: 18.99,
				available: 50,
			},
			{
				name: "Ventolin",
				description: "Also known as Albuterol",
				price: 19.99,
				available: 50,
			},
			{
				name: "Flovent",
				description: "Also known as Fluticasone",
				price: 22.99,
				available: 50,
			},
			{
				name: "Symbicort",
				description: "Also known as Budesonide/Formoterol",
				price: 29.99,
				available: 50,
			},
			{
				name: "Advair",
				description: "Also known as Fluticasone/Salmeterol",
				price: 25.99,
				available: 50,
			},
			{
				name: "Spiriva",
				description: "Also known as Tiotropium",
				price: 30.99,
				available: 50,
			},
			{
				name: "Nasonex",
				description: "Also known as Mometasone",
				price: 15.99,
				available: 50,
			},
			{
				name: "Rhinocort",
				description: "Also known as Budesonide",
				price: 13.99,
				available: 50,
			},
			{
				name: "Clarinex",
				description: "Also known as Desloratadine",
				price: 11.99,
				available: 50,
			},
			{
				name: "Claritin",
				description: "Also known as Loratadine",
				price: 10.99,
				available: 50,
			},
			{
				name: "Zyrtec",
				description: "Also known as Cetirizine",
				price: 12.49,
				available: 50,
			},
			{
				name: "Benadryl",
				description: "Also known as Diphenhydramine",
				price: 7.49,
				available: 50,
			},
			{
				name: "Sudafed",
				description: "Also known as Pseudoephedrine",
				price: 6.99,
				available: 50,
			},
			{
				name: "Mucinex",
				description: "Also known as Guaifenesin",
				price: 14.99,
				available: 50,
			},
			{
				name: "Robitussin",
				description: "Also known as Guaifenesin",
				price: 9.49,
				available: 50,
			},
			{
				name: "Tamiflu",
				description: "Also known as Oseltamivir",
				price: 39.99,
				available: 50,
			},
			{
				name: "Imodium",
				description: "Also known as Loperamide",
				price: 5.99,
				available: 50,
			},
			{
				name: "Pepto-Bismol",
				description: "Also known as Bismuth Subsalicylate",
				price: 7.99,
				available: 50,
			},
			{
				name: "Maalox",
				description: "Also known as Aluminum/Magnesium Hydroxide",
				price: 4.99,
				available: 50,
			},
			{
				name: "Prilosec",
				description: "Also known as Omeprazole",
				price: 12.99,
				available: 50,
			},
			{
				name: "Nexium",
				description: "Also known as Esomeprazole",
				price: 14.99,
				available: 50,
			},
			{
				name: "Zantac",
				description: "Also known as Ranitidine",
				price: 8.99,
				available: 50,
			},
			{
				name: "Pepcid",
				description: "Also known as Famotidine",
				price: 11.49,
				available: 50,
			},
			{
				name: "Tums",
				description: "Also known as Calcium Carbonate",
				price: 4.99,
				available: 50,
			},
			{
				name: "Tagamet",
				description: "Also known as Cimetidine",
				price: 9.99,
				available: 50,
			},
			{
				name: "Lyrica",
				description: "Also known as Pregabalin",
				price: 29.99,
				available: 50,
			},
			{
				name: "Neurontin",
				description: "Also known as Gabapentin",
				price: 18.99,
				available: 50,
			},
			{
				name: "OxyContin",
				description: "Also known as Oxycodone",
				price: 32.99,
				available: 50,
			},
			{
				name: "Percocet",
				description: "Also known as Oxycodone/Acetaminophen",
				price: 24.99,
				available: 50,
			},
			{
				name: "Vicodin",
				description: "Also known as Hydrocodone/Acetaminophen",
				price: 19.99,
				available: 50,
			},
			{
				name: "Ultram",
				description: "Also known as Tramadol",
				price: 15.99,
				available: 50,
			},
			{
				name: "Morphine",
				description: "Also known as Morphine",
				price: 10.99,
				available: 50,
			},
			{
				name: "Dilaudid",
				description: "Also known as Hydromorphone",
				price: 21.99,
				available: 50,
			},
			{
				name: "Suboxone",
				description: "Also known as Buprenorphine/Naloxone",
				price: 89.99,
				available: 50,
			},
			{
				name: "Narcan",
				description: "Also known as Naloxone",
				price: 37.99,
				available: 50,
			},
			{
				name: "Vivitrol",
				description: "Also known as Naltrexone",
				price: 1229.99,
				available: 50,
			},
			{
				name: "Proair",
				description: "Also known as Albuterol",
				price: 18.99,
				available: 50,
			},
			{
				name: "Xarelto",
				description: "Also known as Rivaroxaban",
				price: 46.99,
				available: 50,
			},
			{
				name: "Eliquis",
				description: "Also known as Apixaban",
				price: 50.99,
				available: 50,
			},
			{
				name: "Lovenox",
				description: "Also known as Enoxaparin",
				price: 75.99,
				available: 50,
			},
			{
				name: "Pradaxa",
				description: "Also known as Dabigatran",
				price: 49.99,
				available: 50,
			},
			{
				name: "Synthroid",
				description: "Also known as Levothyroxine",
				price: 8.99,
				available: 50,
			},
			{
				name: "Armour Thyroid",
				description: "Also known as Thyroid",
				price: 34.99,
				available: 50,
			},
			{
				name: "Cymbalta",
				description: "Also known as Duloxetine",
				price: 19.99,
				available: 50,
			},
		],
	});

	await prisma.invoice.createMany({
		data: [
			{
				id: "invoice-1",
				status: "Unpaid",
				createdAt: "2024-08-11T14:14:01.513Z",
				updatedAt: "2024-08-11T14:14:01.513Z",
				patientId: "patient-1",
			},
			{
				id: "invoice-2",
				status: "Paid",
				createdAt: "2024-08-11T14:14:01.535Z",
				updatedAt: "2024-08-11T14:14:01.535Z",
				patientId: "patient-2",
			},
		],
	});
	await prisma.invoice_Medication.createMany({
		data: [
			{
				id: "9e93d299-0b09-412e-b271-c02b4813dbab",
				quantity: 2,
				invoiceId: "invoice-1",
				medicationId: "med-1",
			},
			{
				id: "7a6ecd81-f7d2-427e-99fa-87a61ddbdf8e",
				quantity: 1,
				invoiceId: "invoice-2",
				medicationId: "med-2",
			},
		],
	});
	await prisma.patientRecord.createMany({
		data: [
			{
				id: "22abb26b-9361-4e0b-b16c-7f91cf333818",
				patientType: "Out",
				patientCondition: "Mild",
				allergies: ["Peanuts"],
				familyHistory: "myopia",
				height: 184,
				weight: 55,
				bloodPressure: "120/80",
				temperature: null,
				bloodType: "B+",
				patientId: "9206f122-5800-4126-a557-dbbfc4b03ea0",
			},
		],
	});

	await prisma.workingHours.createMany({
		data: [
			{
				id: "thur-wh",
				date: "Thursday",
				from: 9,
				to: 17,
				doctorId: "84217cb9-4af4-4a92-941d-3d26fb64e2de",
			},
			{
				id: "sat-wh",
				date: "Saturday",
				from: 9,
				to: 17,
				doctorId: "84217cb9-4af4-4a92-941d-3d26fb64e2de",
			},
			{
				id: "fri-wh",
				date: "Friday",
				from: 9,
				to: 17,
				doctorId: "84217cb9-4af4-4a92-941d-3d26fb64e2de",
			},
		],
	});

	await prisma.service.createMany({
		data: [
			{
				id: "service-1",
				name: "Consultation",
				description: "Service provided by doctor to patient",
				price: 200,
			},
			{
				id: "service-2",
				name: "Blood Test",
				description: "Comprehensive blood test",
				price: 30,
			},
			{
				id: "service-3",
				name: "X-Ray",
				description: "Chest X-ray",
				price: 75,
			},
		],
	});
}

main()
	.then(() => console.log("Data seeded successfully"))
	.catch((e) => console.error(e))
	.finally(async () => {
		await prisma.$disconnect();
	});
